version: "3"

services:
  xccgraph:
    image: pdobry/xccgraph:latest
    container_name: xccgraph
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xccgraph.entrypoints=web"
      - "traefik.http.routers.xccgraph.rule=PathPrefix(`/topeni`)"
      - "traefik.http.services.xccgraph.loadbalancer.server.port=80"
      - "traefik.http.middlewares.xccgraph-stripprefix.stripprefix.prefixes=/topeni"
      - "traefik.http.middlewares.xccgraph-redirect.redirectregex.regex=^(https?)://([^/]+)/topeni$$"
      - "traefik.http.middlewares.xccgraph-redirect.redirectregex.replacement=$${1}://$${2}/topeni/"
      - "traefik.http.routers.xccgraph.middlewares=xccgraph-redirect,xccgraph-stripprefix"
    tty: true
    environment:
      - TZ=Europe/Prague
      - XCC_USERNAME=
      - XCC_PASSWORD=
      - XCC_HOSTNAME=xcc.lan
#      - SCHEDULER_ENVIRONMENT=prod
    volumes:
      - ../xccdata:/var/xccdata